// Mocks generated by Mockito 5.4.5 from annotations
// in movie_explorer_app/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_explorer_app/core/resources/data_state.dart' as _i2;
import 'package:movie_explorer_app/features/populars/domain/entities/populars_entity.dart'
    as _i5;
import 'package:movie_explorer_app/features/populars/domain/repositories/populars_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PopularsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularsRepository extends _i1.Mock
    implements _i3.PopularsRepository {
  MockPopularsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<_i5.PopularsEntity>> getPopulars(int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopulars,
          [page],
        ),
        returnValue: _i4.Future<_i2.DataState<_i5.PopularsEntity>>.value(
            _FakeDataState_0<_i5.PopularsEntity>(
          this,
          Invocation.method(
            #getPopulars,
            [page],
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i5.PopularsEntity>>);
}
